---
- name: Ensure {{ record_type }} record for each configured service
  ansible.builtin.include_tasks: manage_record.yml
  loop: "{{ active_services }}"
  loop_control:
    loop_var: dns_service
    label: "{{ dns_service.name }}"
  when: lookup('vars', dns_service.name + '_domain', default='') != ''
