---
- name: Fetch OVH API time
  uri:
    url: "https://{{ ovh_endpoint_url | default('eu.api.ovh.com') }}/1.0/auth/time"
    method: GET
    return_content: true
    status_code: 200
  register: ovh_time_response
  delegate_to: localhost
  become: no
  run_once: true
  when: dns_zone is defined

- name: Ensure A records exist
  include_tasks: ensure_record.yml
  vars:
    record_type: "A"
    target_value: "{{ ansible_host }}"
  when: dns_zone is defined

- name: Ensure AAAA records exist
  include_tasks: ensure_record.yml
  vars:
    record_type: "AAAA"
    target_value: "{{ ansible_host_v6 }}"
  when:
    - dns_zone is defined
    - ansible_host_v6 is defined

- name: Refresh DNS zone
  vars:
    ovh_request_url: "https://{{ ovh_endpoint_url | default('eu.api.ovh.com') }}/1.0/domain/zone/{{ dns_zone }}/refresh"
    ovh_api_timestamp: "{{ ovh_time_response.content | trim }}"
    ovh_signature: "{{ ('$1$' ~ (ovh_application_secret ~ '+' ~ ovh_consumer_key ~ '+POST+' ~ ovh_request_url ~ '++' ~ ovh_api_timestamp) | hash('sha1')) }}"
  uri:
    url: "{{ ovh_request_url }}"
    method: POST
    headers:
      accept: "application/json"
      X-Ovh-Application: "{{ ovh_application_key }}"
      X-Ovh-Consumer: "{{ ovh_consumer_key }}"
      X-Ovh-Timestamp: "{{ ovh_api_timestamp }}"
      X-Ovh-Signature: "{{ ovh_signature }}"
    status_code: 200
  delegate_to: localhost
  become: no
  run_once: true
  when: dns_zone is defined
